#!/usr/bin/env ruby

require 'csv'
require 'pry'

class Customer
	attr_accessor :children, :child, :first_name, :last_name, :birthday, :age, :email

	def initialize
		@children = []
		@child = false
	end

end

class CsvParser

	def self.parse original_filename, new_filename=nil
		new_filename = new_filename || "parsed-#{original_filename}"
		headers = [nil, "Cust Key", nil, "Last Name", nil, "First Name", nil, nil, "Birth Date", nil, "Age", nil, "Email Address"]
		csv = CSV.read(original_filename, headers:headers)
		customers = generate_customers(csv)
		rows = format_rows(customers)
		create_csv(new_filename, rows)
	end

	def self.generate_customers customers_csv
		customers = []
		counter = 1
		puts "Parsing CSV"
		customers_csv[6..-1].each do |row|
			customer = Customer.new
			print "#{counter}... "
			counter += 1
			row.each do |attribute, value|
				case attribute
				when "Last Name"
					customer.last_name = value.capitalize
				when "First Name"
					customer.first_name = value.capitalize
				when "Birth Date"
					customer.birthday = value
				when "Age"
					customer.age = value.to_i
				when "Email Address"
					customer.email = value
				end
			end
			find_parents(customer, customers)
			customers << customer unless customer.child
		end
		print "\n"
		customers
	end

	def self.find_parents customer, customers
		if parent = customers.detect{|c| c.age > customer.age && c.email == customer.email }
			parent.children << customer 
			customer.child = true
		end
	end

	def self.format_rows customers
		customers.map do |c|
			children = c.children.map{|child| [child.first_name, child.birthday]}
			[c.last_name, c.first_name, c.birthday, children].flatten 
		end
	end

	def self.create_csv new_filename, customers
		headers = ["Last name", "First name", "Birthday", "Kid 1 First name", "Kid 1 Birthday", "Kid 2 First name", "Kid 2 Birthday", "Kid 3 First name", "Kid 3 Birthday"]
		CSV.open(new_filename, 'w') do |csv|
			csv << headers
			puts "Creating New CSV"
			counter = 1
			customers.each do |row|
				print "#{counter}... "
				csv.puts row
				counter += 1
			end
			print "\nFINISHED!\n"
		end
	end

end

CsvParser.parse(ARGV[0], ARGV[1])